baseURL =                     "https://firasuke.github.io/DOTSLASHLINUX"
buildDrafts =                 false
buildFuture =                 false
buildExpired =                false
relativeURLs =                false
canonifyURLs =                false
config =                      "config.toml"
contentDir =                  "content"
dataDir =                     "data"
defaultExtension =            "html"
defaultLayout =               "post"
disableLiveReload =           false
enableGitInfo =               false
enableRobotsTXT =             false
disableHugoGeneratorInject =  false
disableKinds = ["robotsTXT"]
disablePathToLower =          false
enableEmoji =                 false
enableMissingTranslationPlaceholders = false
hasCJKLanguage =              false
layoutDir =                   "layouts"
log =                         false
rssLimit =                    6
metaDataFormat =              "toml"
newContentEditor =            "vim"
noChmod =                     false
noTimes =                     false
paginate =                    12
paginatePath =                "page"
pluralizeListTitles =         true
preserveTaxonomyNames =       false
publishdir =                  "public"
staticDir =                   "static"
stepAnalysis =                false
title =                       "Are You Ready? (Y/Y)"
uglyURLs =                    false
verbose =                     false
verboseLog =                  false
watch =                       true

[Permalinks]
  page = "/:sections/:filename/"
  post = "/:sections/:slug/"

[sitemap]
  changefreq = "always"
